### ISSUE TITLE
Bug: ordered list items have margin that looks inconsistent between browsers

### ISSUE THREAD

**Issue by alina7091** [facebook/draft-js#1983]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Margin of ordered list items is inconsistent across browsers.
You can repro it in the demo editor on https://draftjs.org/

Chrome:
<img width="542" alt="screen shot 2019-01-23 at 3 22 45 pm" src="https://user-images.githubusercontent.com/18543042/51643907-10578b80-1f23-11e9-89e7-d53d43aa0fb5.png">

Firefox:
<img width="567" alt="screen shot 2019-01-23 at 3 22 52 pm" src="https://user-images.githubusercontent.com/18543042/51643880-fddd5200-1f22-11e9-81e3-b2cf3127cf78.png">

You can see that OL and UL items are not aligned. In Chrome in does not look _too much_ off, but in Firefox it becomes more noticeable.

I suspect this is happening because of the following css:

```css
.public-DraftStyleDefault-orderedListItem.public-DraftStyleDefault-listLTR:before {
    left: -36px;
    position: absolute;
    text-align: right;
    width: 30px;
}
```

**What is the expected behavior?**
I would expect OL and UL to be aligned in all browsers like
<img width="544" alt="screen shot 2019-01-23 at 3 27 26 pm" src="https://user-images.githubusercontent.com/18543042/51644022-82c86b80-1f23-11e9-958d-6e8d40863aee.png">

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Affected version of Draft: 0.10.5. You can repro in any version of the browser. I was using Chrome 71.0.3578.98 (Official Build) (64-bit) and Firefox 64.0.2 (64-bit)
