### ISSUE TITLE
Why not support to underline numbers

### ISSUE THREAD

**Issue by 007tom** [facebook/draft-js#2573]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

[offical example](https://draftjs.org/) doesn't support underlining numbers

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**

just input a number, nothing changed, but you can underline a text

**What is the expected behavior?**

the number should be underlined like it in MS Word

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

the [offical example](https://draftjs.org/)

**Comment by 007tom** [comment]
Found it, it's a **font** problem !!!
![Aug-24-2020 17-13-03](https://user-images.githubusercontent.com/31362988/91026370-3bd5b700-e62d-11ea-9dfc-5ca746b859d8.gif)


```css
.RichEditor-root {
    background: #fff;
    border: 1px solid #ddd;
    font-family: Georgia,serif;  /* it caused bug and when commented, the bug disappeared */
    font-size: 14px;
    padding: 15px;
}
```
