### ISSUE TITLE
Editor is placed under the placeholder

### ISSUE THREAD

**Issue by barbu110** [facebook/draft-js#556]
When specifying `placeholder` attribute to the `Draft.Editor` component, the placeholder element is rendered with `position: relative` (as far as I can see) so it comes above the editor itself.

![gifrecord_2016-07-22_164239](https://cloud.githubusercontent.com/assets/7272395/17059072/1def14fc-502c-11e6-8bae-92f719589f3d.gif)

**Comment by barbu110** [comment]
My `Editor` component uses custom block-styling which apparently does not merge the original styles with mine, but completely overrides them. So what I was missing was adding CSS rules for the placeholder itself:

```css
.public/DraftEditorPlaceholder/root {
	@extend .RichEditor/block;
	color: var(palette-grey-500);
	position: absolute;
	z-index: 0;
}

.public/DraftEditorPlaceholder/hasFocus {
	color: var(palette-grey-700);
}

.DraftEditorPlaceholder/hidden {
	display: none;
}
```
