### ISSUE TITLE
How to emulate an input tag?

### ISSUE THREAD

**Issue by paulyoung** [facebook/draft-js#657]
This may be considered a feature request but it's more of a question really.

As [discussed on Slack](https://draftjs.slack.com/archives/general/p1473720776000407), I'd like to make an `Editor` behave like an `input` tag.

I think a lot of that boils down to having the content continually scroll to right, and not wrapping.

I've tried [`draft-js-single-line-plugin`](https://github.com/icelab/draft-js-single-line-plugin) but the text still wraps on long lines.

I initially [tried creating a decorator](https://draftjs.slack.com/archives/general/p1473721610000410) which didn't quite work as I wanted, and later got a bit closer with the following CSS:

```css
.public-DraftEditor-content {
  height: 40px;
  overflow: scroll;
  padding-bottom: 10px; /* hide the scrollbar */
}

.public-DraftStyleDefault-block > span {
  white-space: nowrap;
}
```

This still isn't quite right and I don't feel good about styling these elements, but besides that it just seems like there must be a better way.

This could be considered a duplicated of #397, but hopefully this is a more comprehensive report.

Thanks in advance.

cc @makenosound @uiii @jivebot
